name: Push CI

on:
  push:
    branches:
      - main
      - develop

jobs:
  push_tests:
    permissions: write-all
    name: Push E2E Tests
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout the test repository
        uses: actions/checkout@v4

      - name: Install Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Node.js 20.11.1
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
      
      - name: Create reports folder
        run: |
          mkdir -p reports/coverage

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt
          npm install @playwright/test
          npx playwright install-deps
          rfbrowser init

      - name: Run the tests
        run: robot -d ./reports --output output.xml  -v HEADLESS:true -v PIPELINE:true  ./tests

      - name: Validate Test Coverage
        run: |
          python ./resources/libraries/test_coverage_validator.py \
            ./reports/output.xml \
            --min-coverage 80 \
            --output-dir ./reports/coverage

      - name: Upload Push Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: push-test-results
          path: |
            ./reports
            ./reports/coverage
          retention-days: 3
          if-no-files-found: ignore